version: "3.9"
services:
  niyoapp:
    build: .
    image: app:niyo
    container_name: niyo_container
    command: sh -c "chmod +x /niyo/migrate.sh && sh /niyo/migrate.sh && chmod +x /niyo/entrypoint.sh && sh /niyo/entrypoint.sh "
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - niyo_db
    volumes:
      - .:/niyo

  niyo_db:
    container_name: niyo_db
    image: postgres:14-alpine
    restart: always
    command: -p 5434
    env_file:
      - .env
    expose:
      - 5434
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  djangonetwork:
    driver: bridge
