# Generated by Django 4.2.3 on 2024-05-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=240, null=True),
        ),
    ]
